### ISSUE TITLE
Authentication fails with Okta SSO user

### ISSUE THREAD

**Issue by justin-self** [Keeper-Security/Commander#293]
This issue has already been raised with Keeper support but wanted to drop it here for awareness.

With Okta provisioned SSO accounts it's not possible to log into Keeper Commander even with a master password set. The result is always "Authentication failed". 

Hoping this gets resolved soon as it has been lingering for over a month now.

**Comment by craiglurey** [comment]
Hi @justin-self I just tested this and it worked for me.  I recall we fixed this very quickly after it was reported.  You have to set an "alternate" master password from the Vault settings screen.  I'll check to make sure it's also in PIP3 but I think it is

**Comment by craiglurey** [comment]
@justin-self send me an email commander@keepersecurity.com and we can troubleshoot.

**Comment by justin-self** [comment]
Thanks Craig. I had been workin with Jonathan and this issue is still unresolved. He was able to reproduce the same behavior and I haven’t heard an update since last week.

Kind regards,

Justin Varner
Principal Security Engineer
Self Financial, Inc.
www.self.inc

**Comment by SKallDay** [comment]
I am experiencing the same issue above as @justin-self. My team and I are all using the keeper terminal to access files and only some of us are running into this authentication error issue. Whole team uses macOS Catalina.

When prompted for the password, email and  2FA, keeper terminal then rejects login in with the "Authentication failed" error msg but is not clear why.  Tried on multiple browsers and apps all credentials are valid and working. Also tried uninstalling and re installing the keepercommander with no luck.

Please let me know if there is a resolution for this issue.

**Comment by craiglurey** [comment]
This has been resolved.  Commander was not selecting the correct salt/iterations for customers with SSO Alternate Master Password in some cases.
